---
title: "Digital Publications"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE,warning = FALSE, message = FALSE)
```

## Digital Publication 

```{r}
library(tidyverse)
library(tidymodels)
library(tidytext)
library(scales)
library(tidylo)
library(themis)
library(textrecipes)
theme_set(theme_bw())
```


```{r}
publications <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-04-05/news_orgs.csv')
```


### Exploratory Data Analysis

Feature Engineering and cleaning datasets


```{r}
publications %>%
  group_by(owner,is_owner_founder) %>%
  count(sort = TRUE) %>%
  drop_na(.) %>%
  head()
```

```{r}
# Feature Engineering 
publications %>%
  mutate(owner = str_trim(owner),
         owner = str_replace(owner,'Nonprofit','Non Profit')) %>%
  separate(owner,c('First_Owner','Second_Owner'),sep = ',|;',fill = 'right',extra = 'merge') %>%
  count(First_Owner, sort = TRUE)%>%
  drop_na(.) %>%
  head()
```






```{r}
publications %>%
  separate(coverage_topics,c('topics','other_topics'),sep = ',',fill = 'right', extra = 'merge') %>%
  group_by(topics) %>%
  count(sort = TRUE) %>%
  head()
```




```{r}
publications %>%
  separate(distribution,c('distribution','other_distribution'),sep = ',',fill = 'right', extra = 'merge') %>%
  group_by(distribution) %>%
  count(sort = TRUE)
  
```





```{r}
publications %>%
  separate(products,c('products','other_products'),sep = ',',fill = 'right', extra = 'merge') %>%
  group_by(products) %>%
  count(sort = TRUE)
```







```{r}
publications %>%
  mutate(total_employees= case_when(
    total_employees=='0' ~'0-2',
    total_employees=='1' ~'0-2',
    total_employees=='2' ~'0-2',
    TRUE~total_employees
  )) %>%
  group_by(total_employees) %>%
  count(sort=TRUE)
```





```{r}
publications %>%
  mutate(country=str_replace(country,'U.S. Virgin Islands','United States')) %>%
  group_by(country) %>%
  count(sort=TRUE)
```


```{r}
publications %>%
  separate(city,c('Principal_city','Other'),sep = ',',fill = 'right', extra = 'merge') %>%
  count(Principal_city, sort=TRUE) %>%
  head()
```



```{r}
publications %>%
  mutate(owner = str_trim(owner),
         owner = str_replace(owner,'Nonprofit','Non Profit')) %>%
  separate(owner,c('First_Owner','Second_Owner'),sep = ',|;',fill = 'right',extra = 'merge')  %>%
  group_by(First_Owner) %>%
  count(sort = TRUE) %>%
  head()
```


```{r}
publications<-publications %>%
  mutate(owner = str_trim(owner),
         owner = str_replace(owner,'Nonprofit','Non Profit')) %>%
  separate(owner,c('First_Owner','Second_Owner'),sep = ',|;',fill = 'right',extra = 'merge') %>%
  separate(coverage_topics,c('topics','other_topics'),sep = ',',fill = 'right', extra = 'merge') %>%
  separate(distribution,c('distribution','other_distribution'),sep = ',',fill = 'right', extra = 'merge') %>%
   mutate(total_employees= case_when(
    total_employees=='0' ~'0-2',
    total_employees=='1' ~'0-2',
    total_employees=='2' ~'0-2',
    TRUE~total_employees
  )) %>%
  separate(products,c('products','other_products'),sep = ',',fill = 'right', extra = 'merge') %>%
  mutate(country=str_replace(country,'U.S. Virgin Islands','United States')) %>%
  select(publication_name,country,First_Owner,is_owner_founder,year_founded,total_employees,products,distribution,topics,summary) %>%
  drop_na(.)
```




```{r}
publications %>%
  group_by(topics,is_owner_founder) %>%
  count(sort = TRUE)%>%
  pivot_wider(names_from = is_owner_founder , values_from = n) %>%
  mutate(Yes=str_replace_na(Yes,0),
         No=str_replace_na(No,0),
         Yes=as.numeric(Yes),
         No=as.numeric(No),
         total=Yes+No,
         pct_yes=Yes/total,
         pct_no=No/total)%>%
  ungroup() %>%
  mutate(topics= fct_reorder(topics,No)) %>%
  ggplot(aes(topics,y=(pct_yes+pct_no)))+
  geom_segment(aes(x=topics,
                   xend=topics,
                   y=pct_no,
                   yend=pct_yes),
               linetype='dashed',
               show.legend = FALSE)+
   geom_point(aes(y = pct_no,
                  colour = 'No',
                  size=pct_no),
                  shape = 20,
                  fill = 'white',
                  stroke = 1)+
  geom_point(aes(y = pct_yes,
                  colour = 'Yes',
                  size=pct_yes), 
                  shape = 20,
                  fill = 'white',
                  stroke = 1)+
  guides(size=FALSE)+
  labs(color = 'Is the owner the founder?',
       y='',
       x='Topics',
       title = 'How are the effects of Founder Owners and Type of News')+
  scale_y_continuous(labels = percent)+
  coord_flip()
```


```{r}
publications %>%
  group_by(topics,country,year_founded) %>%
  count(sort=TRUE) %>%
  group_by(country,year_founded) %>%
  mutate(pct = n/sum(n))%>%
  mutate(topics = fct_reorder(topics,n,sum)) %>%
  ggplot(aes(year_founded,pct,fill=topics)) +
  geom_area()+
  scale_y_continuous(labels = percent) +
  facet_wrap(~country, scales = 'free_x')

  
```

```{r}
publications%>%
  group_by(topics,products) %>%
  count(sort=TRUE) %>%
  ungroup() %>%
  mutate(topics=fct_reorder(topics,n,sum)) %>%
  ggplot(aes(n,topics,fill=products))+
  geom_col()
```

```{r, fig.height=5}
publications%>%
  group_by(topics,distribution,total_employees) %>%
  count(sort=TRUE)%>%
  ungroup() %>%
  #filter(n>1)%>%
  #filter(total_employees=='21 or more')%>%
  mutate(topics=reorder_within(topics,n,distribution)) %>%
  ggplot(aes(n,topics))+
  geom_point(aes(color=total_employees, size=n),alpha=0.4)+
  scale_y_reordered()+
  guides(size='none')+
  facet_wrap(~distribution, scales = 'free_y')
  
  
```




### Modelling 

Modelling distribution 

```{r, fig.height=5}
topics_log_odds <-
  publications %>%
  group_by(topics) %>%
  unnest_tokens(word, summary) %>%
  count(topics, word, sort = TRUE) %>%
  filter(!word %in% tm::stopwords(),
         !str_detect(word,'[0-9]'),
         !word %in% c('news','benito','sanm','it’s','daily')) %>%
  bind_log_odds(topics, word, n)

topics_log_odds %>%
  group_by(topics) %>%
  slice_max(log_odds_weighted, n = 10) %>%
  ungroup() %>%
  ggplot(aes(log_odds_weighted,
    reorder_within(word, log_odds_weighted,topics),
    fill = topics
  )) +
  scale_y_reordered()+
  geom_col(show.legend = FALSE) +
  facet_wrap(vars(topics), scales = "free") 
```




```{r}
set.seed(1234)

multicomplaints_split <- initial_split(publications%>%
                                         select(distribution,year_founded,topics,summary), strata = distribution)

multicomplaints_train <- training(multicomplaints_split)
multicomplaints_test <- testing(multicomplaints_split)


library(hardhat)
sparse_bp <- default_recipe_blueprint(composition = "dgCMatrix")

library(themis)

multicomplaints_rec <-
  recipe(distribution ~ summary+topics,
         data = multicomplaints_train) %>%
  step_unknown(topics) %>%
  step_dummy(topics)%>%
  step_tokenize(summary) %>%
  step_tokenfilter(summary, max_tokens = 20) %>%
  step_tfidf(summary) %>%
  step_downsample(distribution)
multicomplaints_folds <- vfold_cv(multicomplaints_train)
multi_spec <- multinom_reg(penalty = tune(), mixture = 1) %>%
  set_mode("classification") %>%
  set_engine("glmnet")

multi_lasso_wf <- workflow() %>%
  add_recipe(multicomplaints_rec, blueprint = sparse_bp) %>%
  add_model(multi_spec)

smaller_lambda <- grid_regular(penalty(range = c(-5, 0)), levels = 20)
multi_lasso_rs <- tune_grid(
  multi_lasso_wf,
  multicomplaints_folds,
  grid = smaller_lambda,
  control = control_resamples(save_pred = TRUE)
)

multi_lasso_rs
```



```{r}
best_acc <- multi_lasso_rs %>%
  show_best("accuracy")

best_acc
```



```{r}
set.seed(123)
distribution_split <- initial_split(publications%>%mutate(topics=factor(topics))%>%
                                      select(year_founded,distribution,summary,topics), strata = distribution ) 
distribution_train <- training(distribution_split)
distribution_test <- testing(distribution_split)



set.seed(234)
distributions_folds <- vfold_cv(distribution_train, strata = distribution)


```





```{r}
distribution_recipe<-recipe(distribution ~ year_founded+summary, data = distribution_train) %>%
  step_tokenize(summary) %>%
  step_tokenfilter(summary, max_tokens = 200) %>%
  step_tfidf(summary) 

distribution_recipe %>%
  prep() %>%
  juice()
```


```{r}
multi_spec <-
  multinom_reg(penalty = tune(), mixture = 1) %>%
  set_mode("classification") %>%
  set_engine("glmnet")

nber_wf <- workflow(distribution_recipe, multi_spec)

nber_grid <- grid_regular(penalty(range = c(-5, 0)), levels = 10)

doParallel::registerDoParallel()
set.seed(2022)
nber_rs <-
  tune_grid(
    nber_wf,
    distributions_folds,
    grid = nber_grid
  )

nber_rs%>%unnest(.notes)
```

